name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Prepare package for deployment
        run: |
          mkdir package
          cp -r $(ls -A | grep -v package) package/  # Copy all files except 'package'
          tar -czf output.tar.gz -C package .  # Create tar.gz archive
          ls -lah  # List files for debugging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: output.tar.gz
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Deepseekmodel'  # Replace with your actual Azure Web App name
          package: output.tar.gz
