name: Build and deploy Python app to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and Start Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Package Application
        run: |
          mkdir package
          cp -r * ./package
          rm -rf package/venv  # Exclude virtual environment from packaging
          cd package
          tar -czf ../output.tar.gz .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: output-artifact
          path: deploy

      - name: List downloaded files
        run: ls -R deploy

      - name: Deploy to Azure Web App
        id: deploy-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Deepseekmodel'
          package: 'deploy/output.tar.gz'