name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create package directory and archive
        run: |
          mkdir package
          cp -r . package/  # Copy all files to the package folder
          tar -czf output.tar.gz -C package .  # Create tar.gz from package folder
          ls -lah  # List files for debugging

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: output-artifact
          path: .

      - name: Extract artifact
        run: |
          mkdir -p deploy
          tar -xzf release.tar.gz -C deploy
          ls -lah deploy  # Debugging: check extracted files

      - name: Deploy to Azure Web App
        id: deploy-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Deepseekmodel'  # Replace with your actual Azure Web App name
          package: deploy
          restart-policy: always